### ISSUE TITLE
can not generate API docs

### ISSUE THREAD

**Issue by wei-lee** [aerogear/aerogear-ios-sdk#29]
## Description

It looks like the SDK is using [Jazzy](https://github.com/realm/jazzy) to generate the API docs. However, when following the instructions on jazzy, it doesn't work

## Steps to reproduce

This is the command I run:

```
jazzy \
  --clean \
  --author AeroGear \
  --author_url https://www.aerogear.org \
  --github_url https://github.com/aerogear \
  --module-version 0.1.0 \
  --xcodebuild-arguments -scheme,AeroGearSdkExample \
  --module core \
  --output docs/swift_output \
  --theme docs/themes
```

and this is the error I get:

```
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/6d/gvr23qrn6vbbp25_38kztbvc0000gn/T/xcodebuild-E37761DA-9A92-40B1-A04C-A162172D0C55.log
Failed to generate documentation
/Users/weili/.rvm/gems/ruby-2.2.6/gems/jazzy-0.9.1/lib/jazzy/executable.rb:36:in `execute_command': /Users/weili/.rvm/gems/ruby-2.2.6/gems/jazzy-0.9.1/bin/sourcekitten ["doc", "--module-name", "core", "--", "-scheme", "AeroGearSdkExample"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/6d/gvr23qrn6vbbp25_38kztbvc0000gn/T/xcodebuild-E37761DA-9A92-40B1-A04C-A162172D0C55.log

Failed to generate documentation
	from /Users/weili/.rvm/gems/ruby-2.2.6/gems/jazzy-0.9.1/lib/jazzy/sourcekitten.rb:225:in `run_sourcekitten'
	from /Users/weili/.rvm/gems/ruby-2.2.6/gems/jazzy-0.9.1/lib/jazzy/doc_builder.rb:66:in `block in build'
	from /Users/weili/.rvm/gems/ruby-2.2.6/gems/jazzy-0.9.1/lib/jazzy/doc_builder.rb:64:in `chdir'
	from /Users/weili/.rvm/gems/ruby-2.2.6/gems/jazzy-0.9.1/lib/jazzy/doc_builder.rb:64:in `build'
	from /Users/weili/.rvm/gems/ruby-2.2.6/gems/jazzy-0.9.1/bin/jazzy:15:in `<top (required)>'
	from /Users/weili/.rvm/gems/ruby-2.2.6/bin/jazzy:22:in `load'
	from /Users/weili/.rvm/gems/ruby-2.2.6/bin/jazzy:22:in `<main>'
```

I tried run the command from both the root of the SDK and the root of the example app but have the same results.

**Comment by wtrocki** [comment]
Done in https://github.com/aerogear/aerogear-ios-sdk/pull/37
